.cargo/config.toml, .github/workflows/main.yml, waku-sys/build.rs
=> Ci and build

Cargo.lock, waku/Cargo.toml, waku/src/general/mod.rs, waku/src/lib.rs, waku/src/node_management/config.rs, waku/src/node_management/mod.rs, waku/src/node_management/node.rs
Implemented as per [specification](https://rfc.vac.dev/spec/36/#node-management)
=> Node management

Cargo.lock, waku/Cargo.toml, waku/src/decrypt.rs, waku/src/events/mod.rs, waku/src/general/mod.rs, waku/src/lib.rs, waku/src/node/config.rs, waku/src/node/filter.rs, waku/src/node/lightpush.rs, waku/src/node/management.rs, waku/src/node/mod.rs, waku/src/node/peers.rs, waku/src/node/relay.rs, waku/src/node/store.rs
=> Implement remaning stack

.github/workflows/main.yml, Cargo.lock, waku/Cargo.toml, waku/src/decrypt.rs, waku/src/events/mod.rs, waku/src/general/mod.rs, waku/src/lib.rs, waku/src/node/config.rs, waku/src/node/lightpush.rs, waku/src/node/mod.rs, waku/src/node/peers.rs, waku/src/node/relay.rs, waku/tests/node.rs
Fix some deserialisation and API issues and some API polishing. Upgraded vendor folder to use latest stable version with found fixes as well.
=> Main test and extended fixes

Cargo.lock, waku/Cargo.toml, waku/src/lib.rs, waku/src/node/config.rs, waku/src/node/mod.rs, waku/tests/node.rs
Added log level to waku config
=> Waku log level

Cargo.lock, waku-bindings/Cargo.toml, waku-bindings/LICENSE-APACHEv2, waku-bindings/LICENSE-MIT, waku-sys/Cargo.toml, waku-sys/LICENSE-APACHEv2, waku-sys/LICENSE-MIT, waku-sys/build.rs
=> Publish build

waku-bindings/src/general/mod.rs
=> Add constructor to filter subscription

.github/workflows/main.yml, Cargo.lock, waku-bindings/Cargo.toml, waku-bindings/src/lib.rs, waku-bindings/src/node/management.rs, waku-bindings/src/node/mod.rs
Use correct binding inside `waku_stop` method.
=> Use correct binding inside waku_stop method

.github/workflows/auto-author.yml
Ability to auto assign author to the PR.
=> Auto author GH action

.cargo/config.toml, examples/toy-chat/src/main.rs, waku-bindings/src/decrypt.rs, waku-bindings/src/lib.rs, waku-bindings/src/node/discovery.rs, waku-bindings/src/node/filter.rs, waku-bindings/src/node/lightpush.rs, waku-bindings/src/node/management.rs, waku-bindings/src/node/mod.rs, waku-bindings/src/node/peers.rs, waku-bindings/src/node/relay.rs, waku-bindings/src/node/store.rs, waku-bindings/src/utils.rs, waku-bindings/tests/node.rs
Fixes #45 memmory leaks on ffi string bridges.
=> Free strings

Cargo.lock, examples/Cargo.lock, examples/toy-chat/src/main.rs, waku-bindings/Cargo.toml, waku-bindings/src/general/mod.rs, waku-bindings/src/node/config.rs, waku-bindings/src/node/mod.rs, waku-bindings/src/node/store.rs, waku-sys/Cargo.toml
=> Expose local archive query method

Cargo.lock, waku-bindings/Cargo.toml, waku-bindings/src/general/mod.rs, waku-bindings/src/lib.rs, waku-bindings/src/node/discovery.rs, waku-bindings/src/node/management.rs, waku-bindings/src/node/mod.rs, waku-bindings/src/node/peers.rs, waku-bindings/src/node/relay.rs, waku-sys/Cargo.toml
- Fixed missing calls to decode
- Fixed double free bug on creating topics
- Updated vendor
- Updated dependencies
- Added Dns discovery info
=> Get ready for beta 5

Cargo.lock, waku-bindings/Cargo.toml, waku-sys/Cargo.toml
Update vendor with logLevel fix, bump version to `rc.2`.
=> Update vendor with logLevel fix

Cargo.lock, waku-bindings/Cargo.toml, waku-bindings/src/lib.rs, waku-bindings/src/node/config.rs, waku-bindings/src/node/discovery.rs, waku-bindings/src/node/filter.rs, waku-bindings/src/node/mod.rs, waku-sys/Cargo.toml
Adds the `websockets_param` attribute to the node config to enable ws and wss support
=> feat: websockets support

waku-bindings/src/node/management.rs, waku-bindings/src/node/peers.rs
=> fix: waku_peer_count conversion to usize

waku-bindings/Cargo.toml, waku-bindings/src/node/config.rs
=> fix: enable legacy filter

Cargo.lock, waku-bindings/Cargo.toml, waku-sys/Cargo.toml
See https://github.com/waku-org/go-waku/pull/837
=> fix: race condition in peer connector / manager interaction

.github/workflows/codecov.yml, .github/workflows/main.yml, Cargo.lock, examples/Cargo.lock, examples/toy-chat/src/main.rs, waku-bindings/Cargo.toml, waku-bindings/src/events/mod.rs, waku-bindings/src/general/mod.rs, waku-bindings/src/lib.rs, waku-bindings/src/node/filter.rs, waku-bindings/src/node/legacyfilter.rs, waku-bindings/src/node/mod.rs, waku-bindings/src/node/relay.rs, waku-bindings/src/utils.rs, waku-bindings/tests/node.rs, waku-sys/Cargo.toml
Adds filterV2 functions, and updates the API for relay since now it uses a content filter instead of only a pubsub topic
=> feat: add filterv2 functions

waku-bindings/src/node/config.rs, waku-bindings/src/node/mod.rs
Fixes #52 by adding new config items that let you specify DNS Discovery URLs
=> feat: add dns discovery parameters

waku-bindings/src/macros.rs, waku-bindings/src/node/management.rs
- https://github.com/waku-org/waku-rust-bindings/issues/115
=> avoid closure to be dropped in release mode

waku-bindings/src/node/store.rs
Adapting store queries JSON to be compatible with https://github.com/waku-org/nwaku/pull/3366
=> chore: updating store json format to camelCase
